export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    headlinedark: false,
    darkText: false,
    topLine: "活動介紹",
    heading: "楓落景畔遇建成",
    description: `楓落景畔遇建成是建中、成功、中山、景美四校的電資社團共同舉辦的暑假營隊，我們有網頁設計、C++、還有近期熱門的資安課程。就算是零基礎也可以聽得懂 ! 還有各式各樣獨特新奇的神秘活動等著你來一探究竟 ! `,
    imgStart: false,
    img: require("../../images/izcc-icon.jpg"),
    alt: "izcc",
    buttonEnable: true,
    buttonLabel: "課程簡介",
    dark: true,
    cyan: true,
    to: "class",
};
